# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\PythonProjects\ECGB\Load_Dialog.ui'
#
# Created by: PySide2 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_Load_Dialog(object):
    def setupUi(self, Load_Dialog):
        Load_Dialog.setObjectName("Load_Dialog")
        Load_Dialog.resize(410, 180)
        self.verticalLayout = QtWidgets.QVBoxLayout(Load_Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Load_Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ledtPath = QtWidgets.QLineEdit(Load_Dialog)
        self.ledtPath.setObjectName("ledtPath")
        self.horizontalLayout_3.addWidget(self.ledtPath)
        self.btnSearch = QtWidgets.QPushButton(Load_Dialog)
        self.btnSearch.setObjectName("btnSearch")
        self.horizontalLayout_3.addWidget(self.btnSearch)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnLoad = QtWidgets.QPushButton(Load_Dialog)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.btnLoad.setFont(font)
        self.btnLoad.setObjectName("btnLoad")
        self.horizontalLayout_2.addWidget(self.btnLoad)
        self.btnCancel = QtWidgets.QPushButton(Load_Dialog)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.btnCancel.setFont(font)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout_2.addWidget(self.btnCancel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Load_Dialog)
        QtCore.QMetaObject.connectSlotsByName(Load_Dialog)

    def retranslateUi(self, Load_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Load_Dialog.setWindowTitle(_translate("Load_Dialog", "Dialog"))
        self.label.setText(_translate("Load_Dialog", "导入路径"))
        self.btnSearch.setText(_translate("Load_Dialog", "浏览"))
        self.btnLoad.setText(_translate("Load_Dialog", "导入"))
        self.btnCancel.setText(_translate("Load_Dialog", "取消"))
