# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\PythonCode\ECGB\SJ_Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SJ_Dialog(object):
    def setupUi(self, SJ_Dialog):
        SJ_Dialog.setObjectName("SJ_Dialog")
        SJ_Dialog.resize(410, 180)
        self.verticalLayout = QtWidgets.QVBoxLayout(SJ_Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(SJ_Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ledtPath = QtWidgets.QLineEdit(SJ_Dialog)
        self.ledtPath.setObjectName("ledtPath")
        self.horizontalLayout_3.addWidget(self.ledtPath)
        self.btnSearch = QtWidgets.QPushButton(SJ_Dialog)
        self.btnSearch.setObjectName("btnSearch")
        self.horizontalLayout_3.addWidget(self.btnSearch)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.boxHR = QtWidgets.QCheckBox(SJ_Dialog)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.boxHR.setFont(font)
        self.boxHR.setChecked(True)
        self.boxHR.setObjectName("boxHR")
        self.horizontalLayout.addWidget(self.boxHR)
        self.boxRESP = QtWidgets.QCheckBox(SJ_Dialog)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.boxRESP.setFont(font)
        self.boxRESP.setObjectName("boxRESP")
        self.horizontalLayout.addWidget(self.boxRESP)
        self.boxSPO2 = QtWidgets.QCheckBox(SJ_Dialog)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.boxSPO2.setFont(font)
        self.boxSPO2.setObjectName("boxSPO2")
        self.horizontalLayout.addWidget(self.boxSPO2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnSave = QtWidgets.QPushButton(SJ_Dialog)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.btnSave.setFont(font)
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout_2.addWidget(self.btnSave)
        self.btnCancel = QtWidgets.QPushButton(SJ_Dialog)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.btnCancel.setFont(font)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout_2.addWidget(self.btnCancel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(SJ_Dialog)
        QtCore.QMetaObject.connectSlotsByName(SJ_Dialog)

    def retranslateUi(self, SJ_Dialog):
        _translate = QtCore.QCoreApplication.translate
        SJ_Dialog.setWindowTitle(_translate("SJ_Dialog", "Dialog"))
        self.label.setText(_translate("SJ_Dialog", "保存路径"))
        self.btnSearch.setText(_translate("SJ_Dialog", "浏览"))
        self.boxHR.setText(_translate("SJ_Dialog", "心电"))
        self.boxRESP.setText(_translate("SJ_Dialog", "呼吸"))
        self.boxSPO2.setText(_translate("SJ_Dialog", "血氧/脉率"))
        self.btnSave.setText(_translate("SJ_Dialog", "保存"))
        self.btnCancel.setText(_translate("SJ_Dialog", "取消"))
